export default data = [
  {
    name: 'AWS certified Cloud Practitioner',
    getDate: '2021/07/24',
    updateDate: '2021/07/24',
    detail: 'この資格はAWSのクラウドの基礎知識を問う資格です。',
    imageUrl: require('../assets/images/aws-certified-cloud-practitioner.png'),
    level: 1,
  },
  {
    name: 'AWS certified Solutions Architect Associate',
    getDate: '2021/10/12',
    updateDate: '2021/10/12',
    detail: 'この資格はAWSのクラウドの設計能力を問う資格です。',
    imageUrl: require('../assets/images/aws-certified-solutions-architect-associate.png'),
    level: 2,
  },
  {
    name: 'AWS certified Developer Associate',
    getDate: '2022/4/30',
    updateDate: '2022/4/30',
    detail: 'この資格はAWSのクラウドの開発能力を問う資格です。',
    imageUrl: require('../assets/images/aws-certified-developer-associate.png'),
    level: 2,
  },
  {
    name: 'AWS certified Sysops Administrator Associate',
    getDate: '2022/7/3',
    updateDate: '2022/7/3',
    detail: 'この資格はAWSのクラウドの運用能力を問う資格です。',
    imageUrl: require('../assets/images/aws-certified-sysops-administrator-associate.png'),
    level: 2,
  },
  {
    name: 'LPIC Level1',
    getDate: '2022/7/30',
    updateDate: '2022/7/30',
    detail: 'この資格はLinuxの基礎知識を問う資格です。',
    imageUrl: require('../assets/images/Lpic-1.jpeg'),
    level: 2,
  },
  {
    name: 'AWS certified Solutions Architect Professional',
    getDate: '2022/8/30',
    updateDate: '2022/8/30',
    detail: 'この資格はAWSのクラウドの高い設計能力を問う資格です。',
    imageUrl: require('../assets/images/aws-certified-solutions-architect-professional.png'),
    level: 3,
  },
];
